# Generated by Django 5.2.7 on 2025-12-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_no', models.CharField(max_length=50, unique=True, verbose_name='Takip Numarası')),
                ('alici', models.CharField(max_length=100, verbose_name='Alıcı Adı Soyadı')),
                ('adres', models.TextField(verbose_name='Alıcı Adresi')),
                ('durum', models.CharField(choices=[('YOLDA', 'Yolda / İşleniyor'), ('DAGITIMDA', 'Dağıtımda'), ('TESLIM', 'Teslim Edildi'), ('IPTAL', 'İptal Edildi')], default='YOLDA', max_length=10, verbose_name='Mevcut Durum')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Kargo Ücreti (₺)')),
                ('olusturma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Kargo Gönderisi',
                'verbose_name_plural': 'Kargo Gönderileri',
                'ordering': ['-olusturma'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(choices=[('TESLIMAT', 'Teslimat Sorunu'), ('IADE', 'İade/Değişim Talebi'), ('DIGER', 'Diğer')], max_length=50, verbose_name='Ticket Konusu')),
                ('email', models.EmailField(max_length=254, verbose_name='Kullanıcı E-posta')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('durum', models.CharField(choices=[('ACIK', 'Açık (Yeni)'), ('BEKLEMEDE', 'Yanıt Bekleniyor'), ('KAPALI', 'Çözüldü/Kapandı')], default='ACIK', max_length=20, verbose_name='Durum')),
                ('olusturma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Destek Bileti (Ticket)',
                'verbose_name_plural': 'Destek Biletleri (Tickets)',
                'ordering': ['durum', '-olusturma'],
            },
        ),
        migrations.CreateModel(
            name='CargoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konum', models.CharField(max_length=150, verbose_name='Konum/Şube')),
                ('detay', models.CharField(max_length=255, verbose_name='Durum Detayı')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih ve Saat')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecmis', to='cargoposts.cargo', verbose_name='İlgili Kargo')),
            ],
            options={
                'verbose_name': 'Kargo Geçmiş Adımı',
                'verbose_name_plural': 'Kargo Geçmiş Adımları',
                'ordering': ['tarih'],
            },
        ),
    ]
